#修改TNAME: K2P-5.0 中的K2P-5.0为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build Padavan

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get install subversion g++ zlib1g-dev build-essential git \
        python python3 python3-distutils libncurses5-dev gawk gettext unzip \
        file libssl-dev wget libelf-dev ecj fastjar java-propose-classpath
    - name: Clone source code
      run: |
        git clone https://github.com/ysurac/openmptcprouter.git /opt/openmptcprouter
        cd /opt/openmptcprouter
        OMR_TARGET="p2w_r619ac" ./build.sh V=s
    - name: Build Firmware
      run: |
        mkdir -p /opt/images/
        cd /opt/openmptcprouter/p2w_r619ac/source/bin
        sudo mv -f /opt/openmptcprouter/p2w_r619ac/source/bin/*.bin /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      with:
        name: Padavan-packages
        path: /opt/images
